### ISSUE TITLE
VMAlert: "failed to send alerts to addr, 404 page not found"

### ISSUE THREAD

**Issue by arseny-zinchenko** [VictoriaMetrics/helm-charts#1176]
We have VM stack deployed with `victoria-metrics-k8s-stack` version `~0.24.0`.
We have Alertmanager's URL configured via `values.yaml`:
```
  vmalert:
    spec:
      notifier:
        url: "http://vmalertmanager-vm-k8s-stack.ops-monitoring-ns.svc:9093/alertmanager"
```
And we are able to receive alerts, it's working.

But at the same time, we always have an error in logs like this:

> VictoriaMetrics/app/vmalert/rule/group.go:364	group "kubernetes-system-kubelet": errors(1): rule "KubeletTooManyPods": failed to send alerts to addr "http://vmalertmanager-vm-k8s-stack-0.vmalertmanager-vm-k8s-stack.ops-monitoring-ns.svc:9093/api/v2/alerts": invalid SC 404 from "http://vmalertmanager-vm-k8s-stack-0.vmalertmanager-vm-k8s-stack.ops-monitoring-ns.svc:9093/api/v2/alerts"; response body: 404 page not found

I'm not sure from where it's taken, but it's not the `vmalertmanager-vm-k8s-stack` as in my values.
So it seems like VMAlert is trying to send alerts to both `vmalert.spec.notifier.url = vmalertmanager-vm-k8s-stack`, and to the `vmalertmanager-vm-k8s-stack-0.vmalertmanager-vm-k8s-stack`.

I saw that errors since I've started the stack, about a year. Just now went here to finally to try to resolve it.

**Comment by Haleygo** [comment]
Hello,
`http://vmalertmanager-vm-k8s-stack-0.vmalertmanager-vm-k8s-stack.ops-monitoring-ns.svc:9093/api/v2/alerts` is the default notifier for vmalert when `.Values.alertmanager.enabled=ture`.
https://github.com/VictoriaMetrics/helm-charts/blob/20e3142a0f079083457892e4e7051d97758915ed/charts/victoria-metrics-k8s-stack/templates/_helpers.tpl#L126-L132
It should be working since we create a [headless svc](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) for vmalertmanager-vm-k8s-stack, and the purpose is to ensure vmalert sending alert messages to each alertmanager instance when using HA alertmanager.
Could you check your `vmalertmanager-vm-k8s-stack` svc and see if `vmalertmanager-vm-k8s-stack-0.vmalertmanager-vm-k8s-stack.ops-monitoring-ns.svc` is a valid DNS record?

**Comment by arseny-zinchenko** [comment]
Hi, @Haleygo
Can't see anything about "vmalertmanager-vm-k8s-stack-0":

```
$ kk get svc vmalertmanager-vm-k8s-stack -o yaml
...
  selector:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: vm-k8s-stack
    app.kubernetes.io/name: vmalertmanager
    managed-by: vm-operator
  sessionAffinity: None
```

Also, I guess the issue is due to the fact, that I have a specific URI for the Alertmanager, the `/alertmanager` in the `url: "http://vmalertmanager-vm-k8s-stack.ops-monitoring-ns.svc:9093/alertmanager"`

**Comment by Haleygo** [comment]
`vmalertmanager-vm-k8s-stack-0` refers to the pod name, k8s assigns a stable-network-id to each statefulset pod based on it's name, see [this doc](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id) for details. The domain should be valid if a [headless Service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) is in use.
So my question is: Is there a headless service named `vmalertmanager-vm-k8s-stack` in your cluster? If yes, could you verify if the url `http://vmalertmanager-vm-k8s-stack-0.vmalertmanager-vm-k8s-stack.ops-monitoring-ns.svc:9093` is valid?
And the reason of listing all the alertmanager pods as notifiers instead of using service like you do is, vmalert need to send all the alerts to all the alertmanager instances(when cluster mode alertmanager is used), see [this doc](https://docs.victoriametrics.com/vmalert/#ha-vmalert) for details.

**Comment by arseny-zinchenko** [comment]
Hi.
We still have this issue...

Chart version:
```
- name: victoria-metrics-k8s-stack
  version: ~0.27.0
  repository: https://victoriametrics.github.io/helm-charts
```

Logs:
```
error   VictoriaMetrics/app/vmalert/rule/group.go:364   group "general.rules": errors(1): rule "InfoInhibitor": failed to send alerts to addr "http://vmalertmanager-vm-k8s-stack-0.vmalertmanager-vm-k8s-stack.ops-monitoring-ns.svc:9093/api/v2/alerts": invalid SC 404 from "http://vmalertmanager-vm-k8s-stack-0.vmalertmanager-vm-k8s-stack.ops-monitoring-ns.svc:9093/api/v2/alerts"; response body: 404 page not found
```

VMAlert values:
```
  vmalert:
    spec:
      notifier:
        url: "http://vmalertmanager-vm-k8s-stack.ops-monitoring-ns.svc:9093/alertmanager"
```

VMAlert Pod:
```
Containers:
  vmalert:
    Container ID:  containerd://781a5e2deb370bb950f83789c8ac70ff3ba547a855eaacee3bdd50f364cd1fbd
    Image:         victoriametrics/vmalert:v1.103.0
    Image ID:      docker.io/victoriametrics/vmalert@sha256:ec4990f7b00e6cc640529f06616ee25a385b87c719ef9b0952f71054c71be731
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      -datasource.url=http://vmsingle-vm-k8s-stack.ops-monitoring-ns.svc:8429/
      -evaluationInterval=15s
      -httpListenAddr=:8080
      -notifier.url=http://vmalertmanager-vm-k8s-stack-0.vmalertmanager-vm-k8s-stack.ops-monitoring-ns.svc:9093,http://vmalertmanager-vm-k8s-stack.ops-monitoring-ns.svc:9093/alertmanager
```

Here, in the `notifier.url` we have two URLs: the first one is incorrect, e.g. without the `/alertmanager` URI, and the second one is from the values and is working.

Can we just disable the default one? The `vmalertmanager-vm-k8s-stack-0.vmalertmanager-vm-k8s-stack.ops-monitoring-ns.svc:9093`.

**Comment by AndrewChubatiuk** [comment]
do you manage alertmanager in a separate chart?

**Comment by arseny-zinchenko** [comment]
Nope, it's deployed from the `victoria-metrics-k8s-stack`

**Comment by AndrewChubatiuk** [comment]
how do you set `/alertmanager `path prefix then?

**Comment by arseny-zinchenko** [comment]
From the values file.
We have our own chart, and `victoria-metrics-k8s-stack` is deployed via `dependencies`:
```
apiVersion: v2
name: atlas-victoriametrics
description: A Helm chart for Atlas Victoria Metrics kubernetes monitoring stack
type: application
version: 0.1.1
appVersion: "1.17.0"
dependencies:
- name: victoria-metrics-k8s-stack
  version: ~0.27.0
  repository: https://victoriametrics.github.io/helm-charts
  ...
```

So values are:

```
victoria-metrics-k8s-stack:

  vmsingle:
    ingress:
      enabled: true
      ingressClassName: alb
      annotations:
     ...

  vmalert:
    spec:
      notifier:
        url: "http://vmalertmanager-vm-k8s-stack.ops-monitoring-ns.svc:9093/alertmanager"
        
  ...
```

**Comment by AndrewChubatiuk** [comment]
by default alertmanager is serving at `/` and this one serves at `/alertmanager`. How do you pass a path prefix for alertmanager?

**Comment by arseny-zinchenko** [comment]
Ah, I see :-)
With `alertmanager.spec.routePrefix`:

```
victoria-metrics-k8s-stack:

  fullnameOverride: "vm-k8s-stack"
  ...
  kubeControllerManager:
    enabled: false
    
  alertmanager:
    enabled: true
    persistence:
      enabled: true
      storageClass: "gp2-retain"
      size: 100Mi

    spec:
      replicaCount: 1
      resources:
        requests:
          memory: 50Mi
          cpu: 10m
      configSecret: "alertmanager-config"
      routePrefix: "/alertmanager"
```

**Comment by AndrewChubatiuk** [comment]
hey @arseny-zinchenko 
the latest k8s-stack chart was release with a fix

**Comment by arseny-zinchenko** [comment]
@AndrewChubatiuk Hi, Andrew.
Upgraded the chart to the [0.27.5](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.27.5), but nothing changed:

```
$ kk describe pod vmalert-vm-k8s-stack-86d684f889-nb2s2
...
Containers:
  vmalert:
    Container ID:  containerd://ad96fe8e96bd94c434f75cfc930a72e88b20be06eaf7dd7bf41ccf6942a8797f
    Image:         victoriametrics/vmalert:v1.103.0
    Image ID:      docker.io/victoriametrics/vmalert@sha256:ec4990f7b00e6cc640529f06616ee25a385b87c719ef9b0952f71054c71be731
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
     ...
      -notifier.url=http://vmalertmanager-vm-k8s-stack-0.vmalertmanager-vm-k8s-stack.ops-monitoring-ns.svc:9093,http://vmalertmanager-vm-k8s-stack.ops-monitoring-ns.svc:9093/alertmanager
...
```

And the same error in the logs, because `notifier.url` still have no `/alertmanager` URI:
```
error   VictoriaMetrics/app/vmalert/rule/group.go:364   group "vm-health": errors(1): rule "TooManyLogs": failed to send alerts to addr "http://vmalertmanager-vm-k8s-stack-0.vmalertmanager-vm-k8s-stack.ops-monitoring-ns.svc:9093/api/v2/alerts": invalid SC 404 from "http://vmalertmanager-vm-k8s-stack-0.vmalertmanager-vm-k8s-stack.ops-monitoring-ns.svc:9093/api/v2/alerts"; response body: 404 page not found
```

**Comment by AndrewChubatiuk** [comment]
what are the pod labels of vmalert?

**Comment by arseny-zinchenko** [comment]
```
 kk describe pod vmalert-vm-k8s-stack-86d684f889-fwglp
Name:             vmalert-vm-k8s-stack-86d684f889-fwglp
Namespace:        ops-monitoring-ns
Priority:         0
Service Account:  vmalert-vm-k8s-stack
Node:             ip-10-0-38-17.ec2.internal/10.0.38.17
Start Time:       Thu, 17 Oct 2024 12:12:58 +0300
Labels:           app.kubernetes.io/component=monitoring
                  app.kubernetes.io/instance=vm-k8s-stack
                  app.kubernetes.io/name=vmalert
                  managed-by=vm-operator
                  pod-template-hash=86d684f889
Annotations:      <none>
Status:           Running
IP:               10.0.45.160
```

**Comment by AndrewChubatiuk** [comment]
could you please also share vmalert cr labels?
